[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aicalc-sdk"
version = "0.1.0"
description = "Python SDK for AiCalc"
readme = "README.md"
requires-python = ">=3.8"
